version: "2.1"
services:
  db:
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=foobar
      - MONGO_INITDB_ROOT_USERNAME=root
    image: aghost7/mongo-dev:4.1
    network_mode: host
  redis:
    image: redis
    network_mode: host
