# This is for testing the replicated deployment with just one replica
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jokemongo-host-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/jokemongo
---
apiVersion: v1
kind: Secret
metadata:
  name: jokemongo-secrets
data:
  # This is just "sample-password" which is base64 encoded
  db-password: c2FtcGxlLXBhc3N3b3JkCg==
