apiVersion: v1
kind: Service
metadata:
  name: jokemongo
spec:
  ports:
    - port: 8066
      targetPort: 8066
      protocol: TCP
  type: LoadBalancer
  selector:
    app: jokemongo
    tier: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokemongo
  labels:
    app: jokemongo
spec:
  selector:
    matchLabels:
      app: jokemongo
      tier: front
  template:
    metadata:
      labels:
        app: jokemongo
        tier: front
    spec:
      containers:
      - image: aghost7/jokemongo
        name: jokemongo
        env:
          - name: jokemongo.db.url
            value: mongodb://mongo/jokemongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    app: jokemongo
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: jokemongo
spec:
  selector:
    matchLabels:
      app: jokemongo
      tier: db
  # With the way we're set up, we can't use multiple pods. Since
  # kubernetes does a rolling update (brings up a new pod before bringing
  # down the original) by default, we need to instruct it to not do this.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jokemongo
        tier: db
    spec:
      containers:
        - image: mongo:4.1
          name: mongo
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: jokemongo-pv-claim
